name: Check doc generation
on: [push, pull_request]
jobs:
  docs:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        brew install automake boost doxygen graphviz
        ./autogen.sh
        ./configure
    - name: Doxygen version
      run: |
        doxygen --version
    - name: Check
      run: |
        make docs
